create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  task text not null,
  priority text not null default 'Medium',
  is_completed boolean not null default false,
  user_id uuid not null references auth.users(id) on delete cascade
);

alter table public.todos
add column if not exists priority text not null default 'Medium';

alter table public.todos enable row level security;

drop policy if exists "Users can read their own todos" on public.todos;
create policy "Users can read their own todos"
on public.todos
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can create their own todos" on public.todos;
create policy "Users can create their own todos"
on public.todos
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update their own todos" on public.todos;
create policy "Users can update their own todos"
on public.todos
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own todos" on public.todos;
create policy "Users can delete their own todos"
on public.todos
for delete
to authenticated
using (auth.uid() = user_id);
